# Demo title
title: "EdgeAI Based Subject Tracking Demo"

inputs:
    input0:
        source: /dev/video2   
        format: jpeg
        width: 1280
        height: 720
        framerate: 15
    
    input1:
        source: ros   
        format: JPEG #[Allowed: RGB,UYVY,NV12,JPEG]
        width: 1280
        height: 720
        framerate: 0
        ros_input_topic: '/scuttle/camera1/image_raw/compressed' #[Topic to subscribe to]

models:
    model0:
        model_path: /opt/model_zoo/TFL-OD-2020-ssdLite-mobDet-DSP-coco-320x320
        viz_threshold: 0.5
outputs:
    output0:
        sink: fakesink
        width: 1920
        height: 1080
    output1:
        sink: kmssink
        width: 1920
        height: 1080

flows:
    flow0:
        input: input1
        models: [model0]
        outputs: [output1]
        mosaic:
            mosaic0:
                width:  1280
                height: 720
                pos_x:  0
                pos_y:  0